
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from 'sonner';

const SUPABASE_URL = "https://zbgluffhfvmvwxatldqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZ2x1ZmZoZnZtdnd4YXRsZHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODkxNzQsImV4cCI6MjA1ODY2NTE3NH0.2vBwlj9fbQ_fwYdTqXcV75WowcLNzA-KRP3ayKJo8P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'mediacenter-webapp'
    }
  }
});

// Helper function to check if a storage bucket exists
export const checkIfBucketExists = async (bucketName: string): Promise<boolean> => {
  try {
    const { data, error } = await supabase.storage.getBucket(bucketName);
    if (error) {
      console.error(`Error checking if bucket ${bucketName} exists:`, error);
      return false;
    }
    return !!data;
  } catch (error) {
    console.error(`Exception checking if bucket ${bucketName} exists:`, error);
    return false;
  }
};

// Helper function to create a storage bucket
export const createBucket = async (bucketName: string, isPublic: boolean = true): Promise<boolean> => {
  try {
    console.log(`Attempting to create bucket: ${bucketName} with public=${isPublic}`);
    const { data, error } = await supabase.storage.createBucket(bucketName, {
      public: isPublic,
      fileSizeLimit: 10485760 // 10MB file size limit
    });
    
    if (error) {
      console.error(`Error creating bucket ${bucketName}:`, error);
      toast.error(`Failed to create bucket: ${error.message}`);
      return false;
    }
    
    console.log(`Bucket ${bucketName} created successfully:`, data);
    
    // Apply public bucket policy if it's meant to be public
    if (isPublic) {
      try {
        // This line had the TS error - getPublicUrl doesn't return an error property
        // We're just testing if we can get a public URL, so we don't need to check for errors
        const publicUrlData = supabase.storage.from(bucketName).getPublicUrl('test-policy');
        console.log('Testing bucket public access:', publicUrlData);
      } catch (policyError) {
        console.error(`Exception testing bucket policy:`, policyError);
      }
    }
    
    return true;
  } catch (error) {
    console.error(`Exception creating bucket ${bucketName}:`, error);
    toast.error("Failed to set up storage. Please try again later.");
    return false;
  }
};
